# Generated hazard-free Phase 5 randomized test, seed=0x00000001, count=50
addi x1, x0, 3
nop
nop
nop
addi x2, x0, 7
nop
nop
nop
addi x3, x0, 11
nop
nop
nop
addi x4, x0, 19
nop
nop
nop
addi x5, x0, 23
nop
nop
nop
addi x6, x0, 31
nop
nop
nop
addi x7, x0, 37
nop
nop
nop
addi x8, x0, 43
nop
nop
nop
sub x10, x2, x8
nop
nop
nop
add x8, x14, x15
nop
nop
nop
lui x13, 0xf9c
nop
nop
nop
addi x15, x12, -64
nop
nop
nop
auipc x5, 0xa
nop
nop
nop
addi x1, x0, 33
nop
nop
nop
and x7, x0, x7
nop
nop
nop
auipc x8, 0x7
nop
nop
nop
and x13, x14, x9
nop
nop
nop
addi x7, x3, 11
nop
nop
nop
add x12, x10, x13
nop
nop
nop
sw x9, 36(x0)
nop
nop
nop
lw x15, 4(x0)
nop
nop
nop
auipc x4, 0x5
nop
nop
nop
xor x9, x11, x2
nop
nop
nop
auipc x11, 0xc
nop
nop
nop
xor x8, x0, x15
nop
nop
nop
addi x5, x12, -21
nop
nop
nop
sw x6, 28(x0)
nop
nop
nop
lui x9, 0xeb1
nop
nop
nop
or x11, x0, x12
nop
nop
nop
sw x6, 52(x0)
nop
nop
nop
addi x8, x11, 41
nop
nop
nop
auipc x14, 0xb
nop
nop
nop
addi x9, x10, -57
nop
nop
nop
and x11, x5, x5
nop
nop
nop
add x13, x8, x1
nop
nop
nop
add x2, x0, x14
nop
nop
nop
addi x13, x8, 4
nop
nop
nop
add x13, x5, x11
nop
nop
nop
or x2, x5, x5
nop
nop
nop
or x9, x5, x8
nop
nop
nop
or x8, x10, x15
nop
nop
nop
auipc x2, 0xc
nop
nop
nop
xor x7, x6, x8
nop
nop
nop
add x5, x6, x13
nop
nop
nop
addi x4, x0, -27
nop
nop
nop
addi x12, x5, 45
nop
nop
nop
sw x14, 28(x0)
nop
nop
nop
sw x12, 40(x0)
nop
nop
nop
lui x1, 0x6c9
nop
nop
nop
addi x5, x2, 15
nop
nop
nop
or x12, x5, x13
nop
nop
nop
lw x5, 4(x0)
nop
nop
nop
lw x14, 20(x0)
nop
nop
nop
lw x9, 24(x0)
nop
nop
nop
xor x2, x6, x13
nop
nop
nop
lw x4, 48(x0)
nop
nop
nop
or x9, x15, x0
nop
nop
nop
xor x10, x12, x9
nop
nop
nop
addi x0, x0, 123
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
